import type { Question } from "./types";

export const QUESTIONS: Question[] = [
  {id:1,num:1,title:'Two Sum',diff:'Easy',cat:'Hashing',companies:['Amazon','Google','Meta','Flipkart'],pat:'HashMap'},
  {id:2,num:49,title:'Group Anagrams',diff:'Medium',cat:'Hashing',companies:['Amazon','Google','Meta'],pat:'HashMap'},
  {id:3,num:347,title:'Top K Frequent Elements',diff:'Medium',cat:'Hashing',companies:['Amazon','Meta','Flipkart'],pat:'HashMap + Heap'},
  {id:4,num:128,title:'Longest Consecutive Sequence',diff:'Medium',cat:'Hashing',companies:['Google','Meta','Amazon'],pat:'HashSet'},
  {id:5,num:242,title:'Valid Anagram',diff:'Easy',cat:'Hashing',companies:['Amazon','Razorpay'],pat:'HashMap'},
  {id:6,num:217,title:'Contains Duplicate',diff:'Easy',cat:'Hashing',companies:['Amazon','Flipkart'],pat:'HashSet'},
  {id:7,num:3,title:'Longest Substring Without Repeating Chars',diff:'Medium',cat:'Sliding Window',companies:['Amazon','Google','Meta','Razorpay','Zepto'],pat:'Sliding Window'},
  {id:8,num:76,title:'Minimum Window Substring',diff:'Hard',cat:'Sliding Window',companies:['Google','Meta','Amazon'],pat:'Sliding Window'},
  {id:9,num:239,title:'Sliding Window Maximum',diff:'Hard',cat:'Sliding Window',companies:['Google','Swiggy','Zepto'],pat:'Monotonic Deque'},
  {id:10,num:567,title:'Permutation in String',diff:'Medium',cat:'Sliding Window',companies:['Amazon','Google'],pat:'Sliding Window'},
  {id:11,num:438,title:'Find All Anagrams in a String',diff:'Medium',cat:'Sliding Window',companies:['Amazon','Razorpay'],pat:'Sliding Window'},
  {id:12,num:125,title:'Valid Palindrome',diff:'Easy',cat:'Two Pointers',companies:['Meta','Amazon'],pat:'Two Pointers'},
  {id:13,num:15,title:'3Sum',diff:'Medium',cat:'Two Pointers',companies:['Google','Meta','Amazon','Flipkart'],pat:'Sort + Two Pointers'},
  {id:14,num:11,title:'Container With Most Water',diff:'Medium',cat:'Two Pointers',companies:['Google','Meta','Amazon'],pat:'Two Pointers'},
  {id:15,num:42,title:'Trapping Rain Water',diff:'Hard',cat:'Two Pointers',companies:['Google','Meta','Amazon','Flipkart'],pat:'Two Pointers / Mono Stack'},
  {id:16,num:53,title:'Maximum Subarray',diff:'Medium',cat:'Arrays & Strings',companies:['Amazon','Google','Razorpay','Swiggy'],pat:"Kadane's Algorithm"},
  {id:17,num:238,title:'Product of Array Except Self',diff:'Medium',cat:'Arrays & Strings',companies:['Amazon','Meta','Google'],pat:'Prefix & Suffix'},
  {id:18,num:56,title:'Merge Intervals',diff:'Medium',cat:'Arrays & Strings',companies:['Google','Meta','Amazon','Flipkart'],pat:'Sort + Greedy'},
  {id:19,num:55,title:'Jump Game',diff:'Medium',cat:'Arrays & Strings',companies:['Amazon','Zepto'],pat:'Greedy'},
  {id:20,num:45,title:'Jump Game II',diff:'Medium',cat:'Arrays & Strings',companies:['Google','Amazon'],pat:'Greedy'},
  {id:21,num:189,title:'Rotate Array',diff:'Medium',cat:'Arrays & Strings',companies:['Amazon','Flipkart'],pat:'Reverse Trick'},
  {id:22,num:73,title:'Set Matrix Zeroes',diff:'Medium',cat:'Arrays & Strings',companies:['Flipkart','Amazon'],pat:'In-place Flags'},
  {id:23,num:54,title:'Spiral Matrix',diff:'Medium',cat:'Arrays & Strings',companies:['Google','Amazon','Meta'],pat:'Direction Simulation'},
  {id:24,num:153,title:'Find Minimum in Rotated Sorted Array',diff:'Medium',cat:'Binary Search',companies:['Google','Amazon','Flipkart'],pat:'Binary Search'},
  {id:25,num:33,title:'Search in Rotated Sorted Array',diff:'Medium',cat:'Binary Search',companies:['Google','Amazon','Uber'],pat:'Binary Search'},
  {id:26,num:981,title:'Time Based Key-Value Store',diff:'Medium',cat:'Binary Search',companies:['Amazon','Uber','Google'],pat:'Binary Search on Map'},
  {id:27,num:875,title:'Koko Eating Bananas',diff:'Medium',cat:'Binary Search',companies:['Google','Amazon'],pat:'Binary Search on Answer'},
  {id:28,num:1011,title:'Capacity to Ship Packages Within D Days',diff:'Medium',cat:'Binary Search',companies:['Razorpay','Zepto','Flipkart'],pat:'Binary Search on Answer'},
  {id:29,num:20,title:'Valid Parentheses',diff:'Easy',cat:'Stack & Queue',companies:['Amazon','Google','Meta','Razorpay'],pat:'Stack'},
  {id:30,num:155,title:'Min Stack',diff:'Medium',cat:'Stack & Queue',companies:['Amazon','Google','Flipkart'],pat:'Stack Pair'},
  {id:31,num:739,title:'Daily Temperatures',diff:'Medium',cat:'Stack & Queue',companies:['Google','Amazon','Swiggy'],pat:'Monotonic Stack'},
  {id:32,num:84,title:'Largest Rectangle in Histogram',diff:'Hard',cat:'Stack & Queue',companies:['Google','Amazon','Flipkart'],pat:'Monotonic Stack'},
  {id:33,num:735,title:'Asteroid Collision',diff:'Medium',cat:'Stack & Queue',companies:['Amazon','Google'],pat:'Stack'},
  {id:34,num:32,title:'Longest Valid Parentheses',diff:'Hard',cat:'Stack & Queue',companies:['Flipkart','Google'],pat:'Stack / DP'},
  {id:35,num:394,title:'Decode String',diff:'Medium',cat:'Stack & Queue',companies:['Google','Amazon','Razorpay'],pat:'Stack'},
  {id:36,num:206,title:'Reverse Linked List',diff:'Easy',cat:'Linked List',companies:['Amazon','Meta','Google'],pat:'Iteration / Recursion'},
  {id:37,num:21,title:'Merge Two Sorted Lists',diff:'Easy',cat:'Linked List',companies:['Amazon','Google','Meta'],pat:'Merge'},
  {id:38,num:143,title:'Reorder List',diff:'Medium',cat:'Linked List',companies:['Amazon','Meta','Flipkart'],pat:'Slow/Fast Pointer'},
  {id:39,num:142,title:'Linked List Cycle II',diff:'Medium',cat:'Linked List',companies:['Amazon','Google','Flipkart'],pat:"Floyd's Cycle"},
  {id:40,num:146,title:'LRU Cache',diff:'Medium',cat:'Linked List',companies:['Amazon','Google','Meta','Razorpay','Flipkart'],pat:'HashMap + DLL'},
  {id:41,num:1669,title:'Merge In Between Linked Lists',diff:'Medium',cat:'Linked List',companies:['Amazon'],pat:'Linked List Traversal'},
  {id:42,num:287,title:'Find the Duplicate Number',diff:'Medium',cat:'Linked List',companies:['Google','Amazon'],pat:"Floyd's Cycle"},
  {id:43,num:226,title:'Invert Binary Tree',diff:'Easy',cat:'Trees',companies:['Amazon','Meta','Google'],pat:'DFS / BFS'},
  {id:44,num:104,title:'Maximum Depth of Binary Tree',diff:'Easy',cat:'Trees',companies:['Amazon','Google','Razorpay'],pat:'DFS'},
  {id:45,num:110,title:'Balanced Binary Tree',diff:'Easy',cat:'Trees',companies:['Amazon','Google'],pat:'DFS'},
  {id:46,num:101,title:'Symmetric Tree',diff:'Easy',cat:'Trees',companies:['Razorpay','Amazon'],pat:'DFS Mirror'},
  {id:47,num:102,title:'Binary Tree Level Order Traversal',diff:'Medium',cat:'Trees',companies:['Amazon','Google','Meta','Flipkart'],pat:'BFS Queue'},
  {id:48,num:199,title:'Binary Tree Right Side View',diff:'Medium',cat:'Trees',companies:['Meta','Amazon'],pat:'BFS Level-end'},
  {id:49,num:235,title:'Lowest Common Ancestor of BST',diff:'Medium',cat:'Trees',companies:['Amazon','Google','Meta'],pat:'BST Property'},
  {id:50,num:98,title:'Validate Binary Search Tree',diff:'Medium',cat:'Trees',companies:['Amazon','Google'],pat:'DFS + Range'},
  {id:51,num:230,title:'Kth Smallest in BST',diff:'Medium',cat:'Trees',companies:['Google','Amazon','Flipkart'],pat:'Inorder DFS'},
  {id:52,num:105,title:'Construct Binary Tree from Preorder/Inorder',diff:'Medium',cat:'Trees',companies:['Amazon','Google'],pat:'DFS + HashMap'},
  {id:53,num:297,title:'Serialize and Deserialize Binary Tree',diff:'Hard',cat:'Trees',companies:['Google','Meta','Amazon'],pat:'BFS / DFS'},
  {id:54,num:79,title:'Word Search',diff:'Medium',cat:'Trees',companies:['Amazon','Google','Zepto'],pat:'DFS + Backtracking'},
  {id:55,num:200,title:'Number of Islands',diff:'Medium',cat:'Graphs',companies:['Amazon','Google','Meta','Razorpay','Swiggy'],pat:'DFS / BFS'},
  {id:56,num:934,title:'Shortest Bridge',diff:'Medium',cat:'Graphs',companies:['Razorpay','Google'],pat:'DFS + BFS'},
  {id:57,num:133,title:'Clone Graph',diff:'Medium',cat:'Graphs',companies:['Meta','Amazon','Google'],pat:'DFS + HashMap'},
  {id:58,num:207,title:'Course Schedule',diff:'Medium',cat:'Graphs',companies:['Amazon','Google','Meta'],pat:'Topological Sort'},
  {id:59,num:210,title:'Course Schedule II',diff:'Medium',cat:'Graphs',companies:['Amazon','Google'],pat:'Topological Sort'},
  {id:60,num:127,title:'Word Ladder',diff:'Hard',cat:'Graphs',companies:['Razorpay','Amazon','Google'],pat:'BFS Shortest Path'},
  {id:61,num:994,title:'Rotting Oranges',diff:'Medium',cat:'Graphs',companies:['Amazon','Google','Flipkart'],pat:'Multi-source BFS'},
  {id:62,num:787,title:'Cheapest Flights Within K Stops',diff:'Medium',cat:'Graphs',companies:['Amazon','Flipkart'],pat:'Bellman-Ford / BFS'},
  {id:63,num:417,title:'Pacific Atlantic Water Flow',diff:'Medium',cat:'Graphs',companies:['Google','Amazon'],pat:'Reverse DFS from borders'},
  {id:64,num:721,title:'Accounts Merge',diff:'Medium',cat:'Graphs',companies:['Google','Meta','Amazon'],pat:'Union-Find / DFS'},
  {id:65,num:70,title:'Climbing Stairs',diff:'Easy',cat:'Dynamic Programming',companies:['Amazon','Google','Meta'],pat:'1D DP / Fibonacci'},
  {id:66,num:198,title:'House Robber',diff:'Medium',cat:'Dynamic Programming',companies:['Amazon','Google'],pat:'1D DP'},
  {id:67,num:322,title:'Coin Change',diff:'Medium',cat:'Dynamic Programming',companies:['Amazon','Google','Meta','Flipkart'],pat:'Unbounded Knapsack'},
  {id:68,num:300,title:'Longest Increasing Subsequence',diff:'Medium',cat:'Dynamic Programming',companies:['Google','Amazon','Flipkart'],pat:'DP / Binary Search'},
  {id:69,num:72,title:'Edit Distance',diff:'Medium',cat:'Dynamic Programming',companies:['Razorpay','Google','Amazon'],pat:'2D DP'},
  {id:70,num:62,title:'Unique Paths',diff:'Medium',cat:'Dynamic Programming',companies:['Google','Amazon','Flipkart'],pat:'2D DP / Combinatorics'},
  {id:71,num:416,title:'Partition Equal Subset Sum',diff:'Medium',cat:'Dynamic Programming',companies:['Amazon','Google'],pat:'0/1 Knapsack'},
  {id:72,num:279,title:'Perfect Squares',diff:'Medium',cat:'Dynamic Programming',companies:['Zepto','Google'],pat:'BFS / DP'},
  {id:73,num:40,title:'Combination Sum II',diff:'Medium',cat:'Backtracking',companies:['Razorpay','Amazon','Google'],pat:'Backtracking + Pruning'},
  {id:74,num:46,title:'Permutations',diff:'Medium',cat:'Backtracking',companies:['Amazon','Google','Meta'],pat:'Backtracking'},
  {id:75,num:78,title:'Subsets',diff:'Medium',cat:'Backtracking',companies:['Amazon','Meta','Google'],pat:'Backtracking / Bit Mask'},
  {id:76,num:295,title:'Find Median from Data Stream',diff:'Hard',cat:'Heap / Priority Queue',companies:['Google','Amazon','Meta'],pat:'Two Heaps'},
  {id:77,num:692,title:'Top K Frequent Words',diff:'Medium',cat:'Heap / Priority Queue',companies:['Amazon','Google','Flipkart'],pat:'Min Heap + HashMap'},
  {id:78,num:973,title:'K Closest Points to Origin',diff:'Medium',cat:'Heap / Priority Queue',companies:['Meta','Amazon','Google'],pat:'Max Heap'},
  {id:79,num:621,title:'Task Scheduler',diff:'Medium',cat:'Heap / Priority Queue',companies:['Google','Amazon','Meta'],pat:'Greedy + Heap'},
  {id:80,num:1383,title:'Maximum Performance of a Team',diff:'Hard',cat:'Heap / Priority Queue',companies:['Flipkart'],pat:'Greedy + Heap'},
];
